/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anton
 */
public class CalcCie extends javax.swing.JFrame {

    private Double numero1;
    private String operacao;
    private Double numero2;
    private double resultado;

    /**
     * Creates new form CalcCie
     */
    public CalcCie() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblAC = new javax.swing.JButton();
        lbl1 = new javax.swing.JButton();
        lbl4 = new javax.swing.JButton();
        lbl7 = new javax.swing.JButton();
        lbl0 = new javax.swing.JButton();
        lblM = new javax.swing.JButton();
        lbl2 = new javax.swing.JButton();
        lbl5 = new javax.swing.JButton();
        lbl8 = new javax.swing.JButton();
        lblP = new javax.swing.JButton();
        lblD = new javax.swing.JButton();
        lbl3 = new javax.swing.JButton();
        lbl6 = new javax.swing.JButton();
        lbl9 = new javax.swing.JButton();
        lblPor = new javax.swing.JButton();
        lblC = new javax.swing.JButton();
        lblMm = new javax.swing.JButton();
        lblm = new javax.swing.JButton();
        lblS = new javax.swing.JButton();
        lblI = new javax.swing.JButton();
        lble = new javax.swing.JButton();
        lblsen = new javax.swing.JButton();
        lblcos = new javax.swing.JButton();
        lbltan = new javax.swing.JButton();
        lblPi = new javax.swing.JButton();
        lblE3 = new javax.swing.JButton();
        lblE2 = new javax.swing.JButton();
        lblRQ3 = new javax.swing.JButton();
        lblRQ2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(818, 290));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setMinimumSize(new java.awt.Dimension(13, 60));
        jTextArea1.setPreferredSize(new java.awt.Dimension(812, 284));
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("");
        jTextArea1.getAccessibleContext().setAccessibleDescription("");

        lblAC.setText("AC");
        lblAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblACActionPerformed(evt);
            }
        });

        lbl1.setText("1");
        lbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl1ActionPerformed(evt);
            }
        });

        lbl4.setText("4");
        lbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl4ActionPerformed(evt);
            }
        });

        lbl7.setText("7");
        lbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl7ActionPerformed(evt);
            }
        });

        lbl0.setText("0");
        lbl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl0ActionPerformed(evt);
            }
        });

        lblM.setText("x");
        lblM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMActionPerformed(evt);
            }
        });

        lbl2.setText("2");
        lbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl2ActionPerformed(evt);
            }
        });

        lbl5.setText("5");
        lbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl5ActionPerformed(evt);
            }
        });

        lbl8.setText("8");
        lbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl8ActionPerformed(evt);
            }
        });

        lblP.setText(".");
        lblP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPActionPerformed(evt);
            }
        });

        lblD.setText("÷");
        lblD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDActionPerformed(evt);
            }
        });

        lbl3.setText("3");
        lbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl3ActionPerformed(evt);
            }
        });

        lbl6.setText("6");
        lbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl6ActionPerformed(evt);
            }
        });

        lbl9.setText("9");
        lbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl9ActionPerformed(evt);
            }
        });

        lblPor.setText("%");
        lblPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPorActionPerformed(evt);
            }
        });

        lblC.setText("C");
        lblC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCActionPerformed(evt);
            }
        });

        lblMm.setText("±");
        lblMm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMmActionPerformed(evt);
            }
        });

        lblm.setText("-");
        lblm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblmActionPerformed(evt);
            }
        });

        lblS.setText("+");
        lblS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSActionPerformed(evt);
            }
        });

        lblI.setText("=");
        lblI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIActionPerformed(evt);
            }
        });

        lble.setText("e");
        lble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbleActionPerformed(evt);
            }
        });

        lblsen.setText("sen");
        lblsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblsenActionPerformed(evt);
            }
        });

        lblcos.setText("cos");
        lblcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblcosActionPerformed(evt);
            }
        });

        lbltan.setText("tan");
        lbltan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltanActionPerformed(evt);
            }
        });

        lblPi.setText("π");
        lblPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPiActionPerformed(evt);
            }
        });

        lblE3.setText("x³");
        lblE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblE3ActionPerformed(evt);
            }
        });

        lblE2.setText("x²");
        lblE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblE2ActionPerformed(evt);
            }
        });

        lblRQ3.setText("³√x");
        lblRQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRQ3ActionPerformed(evt);
            }
        });

        lblRQ2.setText("²√x");
        lblRQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRQ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcos, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(lbltan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRQ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRQ3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(lblE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblE3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblD, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblM, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                            .addComponent(lblPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblS, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                            .addComponent(lblMm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(lblAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAC)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lblC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl4)
                            .addComponent(lbl5)
                            .addComponent(lbl6)
                            .addComponent(lblm)
                            .addComponent(lblD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblS)
                                .addComponent(lblM)
                                .addComponent(lbl7)
                                .addComponent(lbl9)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl0)
                            .addComponent(lblP)
                            .addComponent(lblI)
                            .addComponent(lblPor)
                            .addComponent(lblMm))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblsen)
                                .addGap(18, 18, 18)
                                .addComponent(lblcos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lble)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRQ3)
                                    .addComponent(lblRQ2))
                                .addGap(18, 18, 18)
                                .addComponent(lblE2)
                                .addGap(18, 18, 18)
                                .addComponent(lblE3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltan)
                            .addComponent(lblPi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMmActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("-%.11f", Math.abs(numero1));
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblMmActionPerformed

    private void lblSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao = "+";
    }//GEN-LAST:event_lblSActionPerformed

    private void lblIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIActionPerformed
        String selecionar;
        numero2=Double.valueOf(jTextArea1.getText());
        if (null!=operacao)switch (operacao) {
            case "+" -> {
                resultado=numero1+numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "-" -> {
                resultado=numero1-numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "*" -> {
                resultado=numero1*numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "/" -> {
                resultado=numero1/numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "%" -> {
                resultado=numero1%numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "π" -> {
                resultado=numero1*numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "e" -> {
                resultado=numero1*numero2;
                selecionar=String.format("%.11f", resultado);
                jTextArea1.setText(selecionar);
            }
        }
    }//GEN-LAST:event_lblIActionPerformed

    private void lblsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblsenActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", Math.sin(numero1));
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblsenActionPerformed

    private void lbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl8ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl8.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl8ActionPerformed

    private void lbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbleActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("2.71828182846");
        operacao = "e";
    }//GEN-LAST:event_lbleActionPerformed

    private void lbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl1ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl1.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl1ActionPerformed

    private void lbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl2ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl2.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl2ActionPerformed

    private void lbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl3ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl3.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl3ActionPerformed

    private void lbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl4ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl4.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl4ActionPerformed

    private void lbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl5ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl5.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl5ActionPerformed

    private void lbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl6ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl6.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl6ActionPerformed

    private void lbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl7ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl7.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl7ActionPerformed

    private void lbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl9ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl9.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl9ActionPerformed

    private void lbl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl0ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl0.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl0ActionPerformed

    private void lblmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblmActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao = "-";
    }//GEN-LAST:event_lblmActionPerformed

    private void lblMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao = "*";
    }//GEN-LAST:event_lblMActionPerformed

    private void lblDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao = "/";
    }//GEN-LAST:event_lblDActionPerformed

    private void lblPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPActionPerformed
        String InserirNumero=jTextArea1.getText() + lblP.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lblPActionPerformed

    private void lblCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_lblCActionPerformed

    private void lblACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblACActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_lblACActionPerformed

    private void lblPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPorActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao = "%";
    }//GEN-LAST:event_lblPorActionPerformed

    private void lblE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblE2ActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", numero1*numero1);
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblE2ActionPerformed

    private void lblPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPiActionPerformed
        numero1 = Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("3.14159265359");
        operacao = "π";
    }//GEN-LAST:event_lblPiActionPerformed

    private void lblE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblE3ActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", numero1*numero1*numero1);
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblE3ActionPerformed

    private void lblRQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRQ2ActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", Math.sqrt(numero1));
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblRQ2ActionPerformed

    private void lblRQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRQ3ActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", Math.cbrt(numero1));
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblRQ3ActionPerformed

    private void lblcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblcosActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", Math.cos(numero1));
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lblcosActionPerformed

    private void lbltanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbltanActionPerformed
        String selecionar;
        numero1 = Double.valueOf(jTextArea1.getText());
        selecionar=String.format("%.11f", Math.tan(numero1));
        jTextArea1.setText(selecionar);
    }//GEN-LAST:event_lbltanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcCie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcCie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcCie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcCie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcCie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lbl0;
    private javax.swing.JButton lbl1;
    private javax.swing.JButton lbl2;
    private javax.swing.JButton lbl3;
    private javax.swing.JButton lbl4;
    private javax.swing.JButton lbl5;
    private javax.swing.JButton lbl6;
    private javax.swing.JButton lbl7;
    private javax.swing.JButton lbl8;
    private javax.swing.JButton lbl9;
    private javax.swing.JButton lblAC;
    private javax.swing.JButton lblC;
    private javax.swing.JButton lblD;
    private javax.swing.JButton lblE2;
    private javax.swing.JButton lblE3;
    private javax.swing.JButton lblI;
    private javax.swing.JButton lblM;
    private javax.swing.JButton lblMm;
    private javax.swing.JButton lblP;
    private javax.swing.JButton lblPi;
    private javax.swing.JButton lblPor;
    private javax.swing.JButton lblRQ2;
    private javax.swing.JButton lblRQ3;
    private javax.swing.JButton lblS;
    private javax.swing.JButton lblcos;
    private javax.swing.JButton lble;
    private javax.swing.JButton lblm;
    private javax.swing.JButton lblsen;
    private javax.swing.JButton lbltan;
    // End of variables declaration//GEN-END:variables
}
