

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anton
 */
public class Calc extends javax.swing.JFrame {
    
    Double numero1;
    Double numero2;
    Double resultado;
    String operacao;
    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl1 = new javax.swing.JButton();
        lbl2 = new javax.swing.JButton();
        lbl3 = new javax.swing.JButton();
        lblA = new javax.swing.JButton();
        lblS = new javax.swing.JButton();
        lbl4 = new javax.swing.JButton();
        lbl5 = new javax.swing.JButton();
        lbl6 = new javax.swing.JButton();
        lblM = new javax.swing.JButton();
        lblD = new javax.swing.JButton();
        lbl7 = new javax.swing.JButton();
        lblP = new javax.swing.JButton();
        lbl8 = new javax.swing.JButton();
        lbl0 = new javax.swing.JButton();
        lbl9 = new javax.swing.JButton();
        lblI = new javax.swing.JButton();
        lblX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lbl1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl1.setText("1");
        lbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl1ActionPerformed(evt);
            }
        });

        lbl2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl2.setText("2");
        lbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl2ActionPerformed(evt);
            }
        });

        lbl3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl3.setText("3");
        lbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl3ActionPerformed(evt);
            }
        });

        lblA.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblA.setText("+");
        lblA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAActionPerformed(evt);
            }
        });

        lblS.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblS.setText("-");
        lblS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSActionPerformed(evt);
            }
        });

        lbl4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl4.setText("4");
        lbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl4ActionPerformed(evt);
            }
        });

        lbl5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl5.setText("5");
        lbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl5ActionPerformed(evt);
            }
        });

        lbl6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl6.setText("6");
        lbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl6ActionPerformed(evt);
            }
        });

        lblM.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblM.setText("*");
        lblM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMActionPerformed(evt);
            }
        });

        lblD.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblD.setText("/");
        lblD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDActionPerformed(evt);
            }
        });

        lbl7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl7.setText("7");
        lbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl7ActionPerformed(evt);
            }
        });

        lblP.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblP.setText(".");
        lblP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPActionPerformed(evt);
            }
        });

        lbl8.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl8.setText("8");
        lbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl8ActionPerformed(evt);
            }
        });

        lbl0.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl0.setText("0");
        lbl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl0ActionPerformed(evt);
            }
        });

        lbl9.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbl9.setText("9");
        lbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl9ActionPerformed(evt);
            }
        });

        lblI.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblI.setText("=");
        lblI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIActionPerformed(evt);
            }
        });

        lblX.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblX.setText("X");
        lblX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblS, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lblP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblI, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblM, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(lblD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl1ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl1.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl1ActionPerformed

    private void lbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl2ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl2.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl2ActionPerformed

    private void lbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl3ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl3.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl3ActionPerformed

    private void lbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl4ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl4.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl4ActionPerformed

    private void lbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl5ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl5.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl5ActionPerformed

    private void lbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl6ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl6.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl6ActionPerformed

    private void lbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl7ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl7.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl7ActionPerformed

    private void lbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl8ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl8.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl8ActionPerformed

    private void lbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl9ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl9.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl9ActionPerformed

    private void lbl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl0ActionPerformed
        String InserirNumero=jTextArea1.getText() + lbl0.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lbl0ActionPerformed

    private void lblPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPActionPerformed
        String InserirNumero=jTextArea1.getText() + lblP.getText();
        jTextArea1.setText(InserirNumero);
    }//GEN-LAST:event_lblPActionPerformed

    private void lblIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIActionPerformed
        String selecionar;
        numero2=Double.valueOf(jTextArea1.getText());
        if (null!=operacao)switch (operacao) {
            case "+" -> {
                resultado=numero1+numero2;
                selecionar=String.format("%.10f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "-" -> {
                resultado=numero1-numero2;
                selecionar=String.format("%.10f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "*" -> {
                resultado=numero1*numero2;
                selecionar=String.format("%.10f", resultado);
                jTextArea1.setText(selecionar);
            }
            case "/" -> {
                resultado=numero1/numero2;
                selecionar=String.format("%.10f", resultado);
                jTextArea1.setText(selecionar);
            }
        }
    }//GEN-LAST:event_lblIActionPerformed

    private void lblAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAActionPerformed
        numero1=Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao="+";
    }//GEN-LAST:event_lblAActionPerformed

    private void lblSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSActionPerformed
        numero1=Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao="-";
    }//GEN-LAST:event_lblSActionPerformed

    private void lblMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMActionPerformed
        numero1=Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao="*";
    }//GEN-LAST:event_lblMActionPerformed

    private void lblDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDActionPerformed
        numero1=Double.valueOf(jTextArea1.getText());
        jTextArea1.setText("");
        operacao="/";
    }//GEN-LAST:event_lblDActionPerformed

    private void lblXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblXActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_lblXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lbl0;
    private javax.swing.JButton lbl1;
    private javax.swing.JButton lbl2;
    private javax.swing.JButton lbl3;
    private javax.swing.JButton lbl4;
    private javax.swing.JButton lbl5;
    private javax.swing.JButton lbl6;
    private javax.swing.JButton lbl7;
    private javax.swing.JButton lbl8;
    private javax.swing.JButton lbl9;
    private javax.swing.JButton lblA;
    private javax.swing.JButton lblD;
    private javax.swing.JButton lblI;
    private javax.swing.JButton lblM;
    private javax.swing.JButton lblP;
    private javax.swing.JButton lblS;
    private javax.swing.JButton lblX;
    // End of variables declaration//GEN-END:variables
}
